
nirsqa( ...
	'mes_file','../INPUTS/data_MES_Probe1.csv', ...
	'project','TESTPROJ', ...
	'subject','TESTSUBJ', ...
	'session','TESTSESS', ...
	'scan','TESTSCAN', ...
	'out_dir','../OUTPUTS' ...
	);

