function write_hb_part(fname,mes, hbheader,data)
format_str = ['%d,' repmat('%0.8f,',1,mes.nchannels) '%d,%s,%d,%d,%d\r\n'];
fid = fopen(fname,'wt');
for h = 1:length(hbheader)
	fprintf(fid,'%s\r\n',hbheader{h});
end
for l = 1:size(data,1)
	fprintf(fid,format_str, ...
		l, ...
		data(l,:), ...
		mes.mark_d(l), ...
		mes.time_d{l}, ...
		mes.bodymovement_d(l), ...
		mes.removalmark_d(l), ...
		mes.prescan_d(l) ...
		);
end
fclose(fid);
return